In [5]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.shape

(891, 12)

In [9]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
67,68,0,3,"Crease, Mr. Ernest James",male,19.0,0,0,S.P. 3464,8.1583,NaN,S
547,548,1,2,"Padro y Manent, Mr. Julian",male,NaN,0,0,SC/PARIS 2146,13.8625,NaN,C
842,843,1,1,"Serepeca, Miss. Augusta",female,30.0,0,0,113798,31.0000,NaN,C
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S

In [10]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
new_df= df[['Name','SibSp','Parch']]

In [14]:
new_df.head()

                                                Name  SibSp  Parch
0                            Braund, Mr. Owen Harris      1      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      1      0
2                             Heikkinen, Miss. Laina      0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      1      0
4                           Allen, Mr. William Henry      0      0

i want to create a feature that there two columns first is about sibling/childs and secound is about parents so by  adding this i make a new coulumn family size ---------> sibsp+parch and then make it as a family type

In [17]:
new_df['family_size'] = df['SibSp']+df['Parch']

/tmp/ipython-input-17-1760234223.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['family_size'] = df['SibSp']+df['Parch']

In [19]:
new_df.head()

,Name,SibSp,Parch,family_size
0,"Braund, Mr. Owen Harris",1,0,1
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,1
2,"Heikkinen, Miss. Laina",0,0,0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,1
4,"Allen, Mr. William Henry",0,0,0

In [22]:
new_df.sample(10)

                                             Name  SibSp  Parch  family_size
462                             Gee, Mr. Arthur H      0      0            0
278                            Rice, Master. Eric      4      1            5
473  Jerwan, Mrs. Amin S (Marie Marthe Thuillard)      0      0            0
437         Richards, Mrs. Sidney (Emily Hocking)      2      3            5
680                           Peters, Miss. Katie      0      0            0
0                         Braund, Mr. Owen Harris      1      0            1
786                     Sjoblom, Miss. Anna Sofia      0      0            0
32                       Glynn, Miss. Mary Agatha      0      0            0
33                          Wheadon, Mr. Edward H      0      0            0
587              Frolicher-Stehli, Mr. Maxmillian      1      1            2

In [36]:
def myfunc(size):
  if size ==1:
    return 1 #alone
  elif 1<size<=4:
    return 2 #small
  else:
    return 3 #big

In [37]:
myfunc(5)

3

In [41]:
new_df['family_type'] = new_df['family_size'].apply(myfunc)

/tmp/ipython-input-41-3604189073.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['family_type'] = new_df['family_size'].apply(myfunc)

In [42]:
new_df.head()

,Name,SibSp,Parch,family_size,family_type
0,"Braund, Mr. Owen Harris",1,0,1,1
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,1,1
2,"Heikkinen, Miss. Laina",0,0,0,3
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,1,1
4,"Allen, Mr. William Henry",0,0,0,3

i also wnat to check that if a woman is married or not`

In [52]:
new_df['Title']=df['Name'].str.split(',',expand =True)[1].str.split('.',expand= True)[0]

/tmp/ipython-input-52-2905219955.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Title']=df['Name'].str.split(',',expand =True)[1].str.split('.',expand= True)[0]

In [58]:
new_df.sample(5)

,Name,SibSp,Parch,family_size,family_type,Title
616,"Danbom, Mr. Ernst Gilbert",1,1,2,2,Mr
76,"Staneff, Mr. Ivan",0,0,0,3,Mr
481,"Frost, Mr. Anthony Wood ""Archie""",0,0,0,3,Mr
181,"Pernot, Mr. Rene",0,0,0,3,Mr
770,"Lievens, Mr. Rene Aime",0,0,0,3,Mr

In [59]:
new_df['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64